[[CUDNN]]
arch = "x86_64"
cuda = "11.0"
git-tree-sha1 = "15c558e5062be2ba30621928d92084a8bf73d04f"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN.download]]
    sha256 = "76148dc326d5601578087494fa08530fed123fefaec5c740c01de24a62af675b"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v9.1.1+0/CUDNN.v9.1.1.x86_64-linux-gnu-cuda+11.0.tar.gz"
[[CUDNN]]
arch = "aarch64"
cuda = "11.0"
cuda_platform = "sbsa"
git-tree-sha1 = "8c77e558e4a0c01a379a30dce93d54965d3311dc"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN.download]]
    sha256 = "1d5b85c89535a0320bd79d9320dfd7d1a578e623110aa39f365f802106237e24"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v9.1.1+0/CUDNN.v9.1.1.aarch64-linux-gnu-cuda_platform+sbsa-cuda+11.0.tar.gz"
[[CUDNN]]
arch = "x86_64"
cuda = "11.0"
git-tree-sha1 = "415412c1cb60ed6942b0561474770dc7986ae15a"
lazy = true
os = "windows"

    [[CUDNN.download]]
    sha256 = "5e583798b634ede3dbc729b708fa8ae7ed7b6645946ee57d893dd3eeb25a0c47"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v9.1.1+0/CUDNN.v9.1.1.x86_64-w64-mingw32-cuda+11.0.tar.gz"
[[CUDNN]]
arch = "x86_64"
cuda = "12.0"
git-tree-sha1 = "0a27534b5374c74293e2e60a2ecceaaf07e81971"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN.download]]
    sha256 = "ad2561fcae9e9abc1d66a854d3a61dc08c3306eb7b9f3f9da39cb8c8a38f0aca"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v9.1.1+0/CUDNN.v9.1.1.x86_64-linux-gnu-cuda+12.0.tar.gz"
[[CUDNN]]
arch = "aarch64"
cuda = "12.0"
cuda_platform = "jetson"
git-tree-sha1 = "f59f15c426dd401b27aedace3ea2b5ec2f556367"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN.download]]
    sha256 = "2f8356aacf4cb631091af78aec0f3905b60d8845ba3e87c56696caaf9ca64924"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v9.1.1+0/CUDNN.v9.1.1.aarch64-linux-gnu-cuda_platform+jetson-cuda+12.0.tar.gz"
[[CUDNN]]
arch = "aarch64"
cuda = "12.0"
cuda_platform = "sbsa"
git-tree-sha1 = "65eb532469aa6a19e3888e5fd34d732d8881eb23"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN.download]]
    sha256 = "1ffa710d1aa7b1eb6d26f726e3868eb6d889b579bedec7c4ccdabf0008498f8b"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v9.1.1+0/CUDNN.v9.1.1.aarch64-linux-gnu-cuda_platform+sbsa-cuda+12.0.tar.gz"
[[CUDNN]]
arch = "x86_64"
cuda = "12.0"
git-tree-sha1 = "854ff9e01350270ca9053120a89ba34eef24c07a"
lazy = true
os = "windows"

    [[CUDNN.download]]
    sha256 = "5ed12801dffb4cd781299ee6b8527fea6ebc6ed22130d2f11ed233f85daf1f46"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v9.1.1+0/CUDNN.v9.1.1.x86_64-w64-mingw32-cuda+12.0.tar.gz"
