[[CUDNN]]
arch = "x86_64"
cuda = "10.2"
git-tree-sha1 = "1763dcaa4fc59ee3d66ef46f7b93abe314a3868a"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN.download]]
    sha256 = "41bedb9b6e8f0848f21ebf168e682439af619eec9c871e090b5dcf27480414df"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v8.2.1+0/CUDNN.v8.2.1.x86_64-linux-gnu-cuda+10.2.tar.gz"
[[CUDNN]]
arch = "x86_64"
cuda = "10.2"
git-tree-sha1 = "13758d4b6cce1e5be121f16aebaac459d5246f62"
lazy = true
os = "windows"

    [[CUDNN.download]]
    sha256 = "d3e73f9cdbee691b106ff242132704a645965b6c54a82a1ba9239ccbb6b4f6d3"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v8.2.1+0/CUDNN.v8.2.1.x86_64-w64-mingw32-cuda+10.2.tar.gz"
[[CUDNN]]
arch = "aarch64"
cuda = "10.2"
git-tree-sha1 = "56ec785a7571c12bc0034a127db2d9b9ffbbe1a7"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN.download]]
    sha256 = "40a6a55b7aa8af54e8c576efb72997b423bd074cbcb6e44f1a5e06665228566c"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v8.2.1+0/CUDNN.v8.2.1.aarch64-linux-gnu-cuda+10.2.tar.gz"
[[CUDNN]]
arch = "x86_64"
cuda = "11.0"
git-tree-sha1 = "63cdad282db3643c755b7bb13630ded55fbd8041"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN.download]]
    sha256 = "9cebd3f3fb25aa6a39d1ac0181ec041caab5e7037a1e56898fd2ae82cdf98aa3"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v8.2.1+0/CUDNN.v8.2.1.x86_64-linux-gnu-cuda+11.0.tar.gz"
[[CUDNN]]
arch = "powerpc64le"
cuda = "11.0"
git-tree-sha1 = "92ee6d8311cccda79bb20c96346f0f2e2ae36810"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN.download]]
    sha256 = "c8938bea03e3b397974582f0501c25820c8168194bb3c74a83394720e60d7786"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v8.2.1+0/CUDNN.v8.2.1.powerpc64le-linux-gnu-cuda+11.0.tar.gz"
[[CUDNN]]
arch = "x86_64"
cuda = "11.0"
git-tree-sha1 = "562435a85c188cac2ae40d9810e39a7596ad2d65"
lazy = true
os = "windows"

    [[CUDNN.download]]
    sha256 = "9421775c7d16639668f8a7ca32bbddf9af7467711b8810ef64e11ed6cc3432bb"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v8.2.1+0/CUDNN.v8.2.1.x86_64-w64-mingw32-cuda+11.0.tar.gz"
[[CUDNN]]
arch = "aarch64"
cuda = "11.0"
git-tree-sha1 = "60cfbfda65d16eef19a851314e8cd0c0ad8219f8"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN.download]]
    sha256 = "d54395c43f33b5656c95e8c1f905f7ac4ea55d0a76f78f784258fbf0b93ded26"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v8.2.1+0/CUDNN.v8.2.1.aarch64-linux-gnu-cuda+11.0.tar.gz"
[[CUDNN]]
arch = "x86_64"
cuda = "11.1"
git-tree-sha1 = "116133b5fff25b22e31660d0e6da172b749c3d30"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN.download]]
    sha256 = "40d83393b19f4ccffe047b9061eee58c60058dad4e9045aa10c0a1b1bdb11cf2"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v8.2.1+0/CUDNN.v8.2.1.x86_64-linux-gnu-cuda+11.1.tar.gz"
[[CUDNN]]
arch = "powerpc64le"
cuda = "11.1"
git-tree-sha1 = "15e8d623f0e7edbb8e9b398ce8b51ea3c43e1819"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN.download]]
    sha256 = "291f909fdbad6a0fe65c5d70cb2fc2ed08b07d758c4b0e8e9e604fb1ebd481f9"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v8.2.1+0/CUDNN.v8.2.1.powerpc64le-linux-gnu-cuda+11.1.tar.gz"
[[CUDNN]]
arch = "x86_64"
cuda = "11.1"
git-tree-sha1 = "58d286360a0a45cc2dcfc9420276ce51fea50742"
lazy = true
os = "windows"

    [[CUDNN.download]]
    sha256 = "8b9e7d7b22561613c3831e6a4e2751992f7cf514de44c14c090cfc39b399397f"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v8.2.1+0/CUDNN.v8.2.1.x86_64-w64-mingw32-cuda+11.1.tar.gz"
[[CUDNN]]
arch = "aarch64"
cuda = "11.1"
git-tree-sha1 = "132ca47a569a75527c120dfdc505dcc1aca21b4c"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN.download]]
    sha256 = "555e7098a3f70073bc69903b6081439aeb0f7054ccb54ddd264f17ed0a54aaad"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v8.2.1+0/CUDNN.v8.2.1.aarch64-linux-gnu-cuda+11.1.tar.gz"
[[CUDNN]]
arch = "x86_64"
cuda = "11.2"
git-tree-sha1 = "6579c1f24652c37d2bdcf17d53d9f3eede47a8f2"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN.download]]
    sha256 = "ee3ba8e91e9f6fdcd4889bcfc17433c2c8314bf9a19da65ae39d5a1e49c5b975"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v8.2.1+0/CUDNN.v8.2.1.x86_64-linux-gnu-cuda+11.2.tar.gz"
[[CUDNN]]
arch = "powerpc64le"
cuda = "11.2"
git-tree-sha1 = "e494d3f4d86c5e282176957bb80a3175b3466116"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN.download]]
    sha256 = "d54b99f600f40d209ec8161be1ada8ef5ea540cc4cb3febcb8e3ae9270e12cc5"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v8.2.1+0/CUDNN.v8.2.1.powerpc64le-linux-gnu-cuda+11.2.tar.gz"
[[CUDNN]]
arch = "x86_64"
cuda = "11.2"
git-tree-sha1 = "e237780bc19db210c6c7b701a1a972f5bf015362"
lazy = true
os = "windows"

    [[CUDNN.download]]
    sha256 = "9aa33a1190cb0f60c03f547bc2e35142643a1d69054e5adce2587d8134995e7e"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v8.2.1+0/CUDNN.v8.2.1.x86_64-w64-mingw32-cuda+11.2.tar.gz"
[[CUDNN]]
arch = "aarch64"
cuda = "11.2"
git-tree-sha1 = "a2a486a9d95c4f7c1bb3d9c972f9d73bb184a062"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN.download]]
    sha256 = "faa31674785c3b330f27259f8a20ef14564b228a9fda47ac2355943ff8663c6e"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v8.2.1+0/CUDNN.v8.2.1.aarch64-linux-gnu-cuda+11.2.tar.gz"
[[CUDNN]]
arch = "x86_64"
cuda = "11.3"
git-tree-sha1 = "bbc8a395763ab28f2a0a76788620672d3c3bf948"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN.download]]
    sha256 = "599ad5fc6673b9833a84bfc988f046c010217f0802341b1fcefa5d08bb9f55ad"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v8.2.1+0/CUDNN.v8.2.1.x86_64-linux-gnu-cuda+11.3.tar.gz"
[[CUDNN]]
arch = "powerpc64le"
cuda = "11.3"
git-tree-sha1 = "8f97e168784611708a6e59540aeb9cb402db8f7b"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN.download]]
    sha256 = "c66e2e9e1902e0a2c137391e9d2d03f87bf09bf71856392b21ed8841e0e160d6"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v8.2.1+0/CUDNN.v8.2.1.powerpc64le-linux-gnu-cuda+11.3.tar.gz"
[[CUDNN]]
arch = "x86_64"
cuda = "11.3"
git-tree-sha1 = "1476f82d4c5057169661732888bd7e2e65a16fb4"
lazy = true
os = "windows"

    [[CUDNN.download]]
    sha256 = "667d68c0119c328a51fb5e20c8d30af99fcc1e64cc917d188951b80798c5301b"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v8.2.1+0/CUDNN.v8.2.1.x86_64-w64-mingw32-cuda+11.3.tar.gz"
[[CUDNN]]
arch = "aarch64"
cuda = "11.3"
git-tree-sha1 = "4d8cd8200509f663a4ba437e221ae416ea68d9bf"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN.download]]
    sha256 = "a33c275fba8c832ae36dc5a90096b0b3f87bad828e77110b79d760da0f1d33a1"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v8.2.1+0/CUDNN.v8.2.1.aarch64-linux-gnu-cuda+11.3.tar.gz"
[[CUDNN]]
arch = "x86_64"
cuda = "11.4"
git-tree-sha1 = "1879737d89350ea72c37a5997bde79b0d425db30"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN.download]]
    sha256 = "6d9e8e67ea1b570d314ec6ce374acd2a642d5ee5af095cf432b8cdd4e541e3d3"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v8.2.1+0/CUDNN.v8.2.1.x86_64-linux-gnu-cuda+11.4.tar.gz"
[[CUDNN]]
arch = "powerpc64le"
cuda = "11.4"
git-tree-sha1 = "f1e81a0295709d113092f8e91d5729e39043d439"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN.download]]
    sha256 = "9763660d73d75c8fdedbcea4dfe333acb673670d43deb0098d0d38b08fe264a3"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v8.2.1+0/CUDNN.v8.2.1.powerpc64le-linux-gnu-cuda+11.4.tar.gz"
[[CUDNN]]
arch = "x86_64"
cuda = "11.4"
git-tree-sha1 = "81b3f6993afc5e384143bf31718209d8a8319290"
lazy = true
os = "windows"

    [[CUDNN.download]]
    sha256 = "8910aa4f5cd5b51b3f3ec1b6056df7559475fccf862cce9ab0e7d84bb3c4c8da"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v8.2.1+0/CUDNN.v8.2.1.x86_64-w64-mingw32-cuda+11.4.tar.gz"
[[CUDNN]]
arch = "aarch64"
cuda = "11.4"
git-tree-sha1 = "9569f93a0a6a0990ed95010ae6849ba3eba6ce80"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN.download]]
    sha256 = "ad99faf581eec9ddde7768311fa3259308d7530b024d403eae20a1a56a135457"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v8.2.1+0/CUDNN.v8.2.1.aarch64-linux-gnu-cuda+11.4.tar.gz"
