[[CUDNN]]
arch = "x86_64"
cuda = "10.2"
git-tree-sha1 = "200f123e57ac824db9ca6ad0f869c996df00c538"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN.download]]
    sha256 = "16fbf1eb64b901c6aa591641aa6d8f13ddab737d0006a9f2b9e2172fc156f65b"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v8.2.4+1/CUDNN.v8.2.4.x86_64-linux-gnu-cuda+10.2.tar.gz"
[[CUDNN]]
arch = "x86_64"
cuda = "10.2"
git-tree-sha1 = "5757cdddba936f0b2c0615f84279e26a62990f61"
lazy = true
os = "windows"

    [[CUDNN.download]]
    sha256 = "64cc31e7251580b95fac33c93b7c94851b42b521727c39579ab6917af4803895"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v8.2.4+1/CUDNN.v8.2.4.x86_64-w64-mingw32-cuda+10.2.tar.gz"
[[CUDNN]]
arch = "aarch64"
cuda = "10.2"
git-tree-sha1 = "15c3d1eec284d88b317eeb7bca073a72e8b1741a"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN.download]]
    sha256 = "f505facc90327760456c8145cef7a7af9e5b2022b49e06dcb82dbeddbf6627f7"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v8.2.4+1/CUDNN.v8.2.4.aarch64-linux-gnu-cuda+10.2.tar.gz"
[[CUDNN]]
arch = "x86_64"
cuda = "11.0"
git-tree-sha1 = "571dc1e89e3a8d54f3aae43f5023577874874575"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN.download]]
    sha256 = "3a35ae74cfbdd415f7ebb02117bad98d04edfe3afe37f8726c4e9755b3df438f"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v8.2.4+1/CUDNN.v8.2.4.x86_64-linux-gnu-cuda+11.0.tar.gz"
[[CUDNN]]
arch = "powerpc64le"
cuda = "11.0"
git-tree-sha1 = "ed5f941067b8b9cd6c3c88914a30595bd7b84ac2"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN.download]]
    sha256 = "b0db68dc2091445731638e4f1405df35164cb45b0c1c64253899c80a2d1ed21c"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v8.2.4+1/CUDNN.v8.2.4.powerpc64le-linux-gnu-cuda+11.0.tar.gz"
[[CUDNN]]
arch = "x86_64"
cuda = "11.0"
git-tree-sha1 = "5dae7d564685e347eea114bb823e500f5568bd75"
lazy = true
os = "windows"

    [[CUDNN.download]]
    sha256 = "f75bbfde9c98eb125cb5edda5d96295c828f503689d0e3cbc132bc1345fb9cd8"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v8.2.4+1/CUDNN.v8.2.4.x86_64-w64-mingw32-cuda+11.0.tar.gz"
[[CUDNN]]
arch = "aarch64"
cuda = "11.0"
git-tree-sha1 = "00a1de0b49638c301eea8e8a9ca8c9c255200119"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN.download]]
    sha256 = "16fd4a6f2b61d609a7416c8f24556e1944e0b5fad58228b7d3429618d09398c1"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v8.2.4+1/CUDNN.v8.2.4.aarch64-linux-gnu-cuda+11.0.tar.gz"
