[[CUDNN]]
arch = "x86_64"
cuda = "11.0"
git-tree-sha1 = "e0c875e325093e68e249231281628226d425bd45"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN.download]]
    sha256 = "16d513063197de7148565269eb5c1462b7b3c3628b0319c74f0cb7feb824db76"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v8.9.2+0/CUDNN.v8.9.2.x86_64-linux-gnu-cuda+11.0.tar.gz"
[[CUDNN]]
arch = "powerpc64le"
cuda = "11.0"
git-tree-sha1 = "ec1c5e34a75e20057a6ef7541deba2f6d619201b"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN.download]]
    sha256 = "db2adaab31f06c91b79656674036614844073c90dfa4db0f25d44d75d0c8cfbc"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v8.9.2+0/CUDNN.v8.9.2.powerpc64le-linux-gnu-cuda+11.0.tar.gz"
[[CUDNN]]
arch = "x86_64"
cuda = "11.0"
git-tree-sha1 = "45a4fe28bb3bb156ee03af394a2083f850714159"
lazy = true
os = "windows"

    [[CUDNN.download]]
    sha256 = "511764fd6971f894283eb9c66c5284630be2ad69a0f0103a4de3c9b9e19ab137"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v8.9.2+0/CUDNN.v8.9.2.x86_64-w64-mingw32-cuda+11.0.tar.gz"
[[CUDNN]]
arch = "aarch64"
cuda = "11.0"
git-tree-sha1 = "6122325a9ef15ecb9be9f0e67d21922bcc48bc02"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN.download]]
    sha256 = "680d283d23e3ac8d094e5defdb095bd5d60f09e7a91e8d51411f5f5660a4e09e"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v8.9.2+0/CUDNN.v8.9.2.aarch64-linux-gnu-cuda+11.0.tar.gz"
[[CUDNN]]
arch = "x86_64"
cuda = "12.0"
git-tree-sha1 = "3895913001a50581c4e38ab1ef78fcc63317f25e"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN.download]]
    sha256 = "6be4a7a1c03454eae240de5fa3dc4747fec38cee8413d45d380231adf76f84d7"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v8.9.2+0/CUDNN.v8.9.2.x86_64-linux-gnu-cuda+12.0.tar.gz"
[[CUDNN]]
arch = "powerpc64le"
cuda = "12.0"
git-tree-sha1 = "4d98b82c47d7afa393b6425e9544c24f137e0404"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN.download]]
    sha256 = "414cd3fe0bf1141910d63275db0278d71287edb39c34932b48ded3aea7976a3a"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v8.9.2+0/CUDNN.v8.9.2.powerpc64le-linux-gnu-cuda+12.0.tar.gz"
[[CUDNN]]
arch = "x86_64"
cuda = "12.0"
git-tree-sha1 = "16e84761606aa0575b2f0ae05d2e861dac35f086"
lazy = true
os = "windows"

    [[CUDNN.download]]
    sha256 = "83ce659bc0d3decb9e912b296d63f38482c8b3463e73c476468054bd2bf51042"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v8.9.2+0/CUDNN.v8.9.2.x86_64-w64-mingw32-cuda+12.0.tar.gz"
[[CUDNN]]
arch = "aarch64"
cuda = "12.0"
git-tree-sha1 = "a6ab3ad2830e4d7c725d80a867d7f36a9c604ae9"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN.download]]
    sha256 = "c10e6a4b290243d0947b62f0bced454115d1e1f399937af2acedee052e3ac2ee"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v8.9.2+0/CUDNN.v8.9.2.aarch64-linux-gnu-cuda+12.0.tar.gz"
