[[CUDNN]]
arch = "x86_64"
cuda = "12.0"
git-tree-sha1 = "e53e92933b0a08a41fdcf79725c4e989827a7555"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN.download]]
    sha256 = "0ae798ad27b78ff13879588ffc76b40a5afb88abab8035d74369b3e9102f4ab7"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v9.17.1+0/CUDNN.v9.17.1.x86_64-linux-gnu-cuda+12.0.tar.gz"
[[CUDNN]]
arch = "aarch64"
cuda = "12.0"
cuda_platform = "jetson"
git-tree-sha1 = "ad4ae6a630f5388c218742d7c55ee4129299c23d"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN.download]]
    sha256 = "cfdeac885eef104d182ac392679844c3b1ce7a630fcb28433e91035cd4b0d7c7"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v9.17.1+0/CUDNN.v9.17.1.aarch64-linux-gnu-cuda_platform+jetson-cuda+12.0.tar.gz"
[[CUDNN]]
arch = "aarch64"
cuda = "12.0"
cuda_platform = "sbsa"
git-tree-sha1 = "a53c8b0bbfc9aab2d7a4c87fe39453db832dd1bc"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN.download]]
    sha256 = "f0c6e2888f0b4baa34376175009fbdfb5f2b4187cc0ad433874d8cdc6baa9332"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v9.17.1+0/CUDNN.v9.17.1.aarch64-linux-gnu-cuda_platform+sbsa-cuda+12.0.tar.gz"
[[CUDNN]]
arch = "x86_64"
cuda = "12.0"
git-tree-sha1 = "5b19843137a713845598527bd3eedeb9f637cd57"
lazy = true
os = "windows"

    [[CUDNN.download]]
    sha256 = "4d2066510e386cafe18d9e73eb288eeb260a82725d1133d6b13031bbe643deae"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v9.17.1+0/CUDNN.v9.17.1.x86_64-w64-mingw32-cuda+12.0.tar.gz"
[[CUDNN]]
arch = "x86_64"
cuda = "13.0"
git-tree-sha1 = "5a693996a3ede536c7fe531c0274057a3e9752cd"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN.download]]
    sha256 = "4af77965b02c76940f14d3eab070b5101753560cca0ba234d4ecc744605e8447"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v9.17.1+0/CUDNN.v9.17.1.x86_64-linux-gnu-cuda+13.0.tar.gz"
[[CUDNN]]
arch = "aarch64"
cuda = "13.0"
git-tree-sha1 = "40825abae57018c7c08a86438f558379dedd253a"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN.download]]
    sha256 = "e738342cef6ca9c7a1684a5652d5661c2282349267173489e13234677b9b221f"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v9.17.1+0/CUDNN.v9.17.1.aarch64-linux-gnu-cuda+13.0.tar.gz"
[[CUDNN]]
arch = "x86_64"
cuda = "13.0"
git-tree-sha1 = "aae0cac59c6741bcf6b54192990a4b3af9461d84"
lazy = true
os = "windows"

    [[CUDNN.download]]
    sha256 = "6e1aaa8e164c0f39b49e48f83a545a93ce00f16cb23c998587852b118c011adb"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v9.17.1+0/CUDNN.v9.17.1.x86_64-w64-mingw32-cuda+13.0.tar.gz"
