[[CUDNN]]
arch = "x86_64"
cuda = "11.0"
git-tree-sha1 = "004af831187c1dac1de0f62b6b45f83b102354da"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN.download]]
    sha256 = "c64506815bb7bfc5d87281f962a880083b6c18786e73c6c097c90fd915f50e2a"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v9.10.0+0/CUDNN.v9.10.0.x86_64-linux-gnu-cuda+11.0.tar.gz"
[[CUDNN]]
arch = "aarch64"
cuda = "11.0"
cuda_platform = "sbsa"
git-tree-sha1 = "d398b6a93dde5f772e24951d89bca3068c22b38e"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN.download]]
    sha256 = "c5e7ad949280e7defac184d00352fcbd667b1e758ba46100d257b3c5f656fcbc"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v9.10.0+0/CUDNN.v9.10.0.aarch64-linux-gnu-cuda_platform+sbsa-cuda+11.0.tar.gz"
[[CUDNN]]
arch = "x86_64"
cuda = "11.0"
git-tree-sha1 = "84232dd1311fdfe15451f149527948ccbbe93435"
lazy = true
os = "windows"

    [[CUDNN.download]]
    sha256 = "5e01e5160de1754c2e58171f2d0340ac6dbe6252ec687d709c9fd8e40a9da529"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v9.10.0+0/CUDNN.v9.10.0.x86_64-w64-mingw32-cuda+11.0.tar.gz"
[[CUDNN]]
arch = "x86_64"
cuda = "12.0"
git-tree-sha1 = "2eb570b35b597d106228383c5cfa490f4bf538ee"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN.download]]
    sha256 = "be66b3ffc5508ce4e61589a306c9c6d8f7aef04cd03df493c5e6dfc5a609b2d9"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v9.10.0+0/CUDNN.v9.10.0.x86_64-linux-gnu-cuda+12.0.tar.gz"
[[CUDNN]]
arch = "aarch64"
cuda = "12.0"
cuda_platform = "jetson"
git-tree-sha1 = "e8ebed8a84983cdb924aee99d6626ce5b9b0c0f8"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN.download]]
    sha256 = "40551816cec3273bd892189cf38336706049057100fd027d63118f81546a4819"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v9.10.0+0/CUDNN.v9.10.0.aarch64-linux-gnu-cuda_platform+jetson-cuda+12.0.tar.gz"
[[CUDNN]]
arch = "aarch64"
cuda = "12.0"
cuda_platform = "sbsa"
git-tree-sha1 = "4ccc2e8fd9fe835d04b7083eb9fd40c2219bb2fb"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN.download]]
    sha256 = "5c75554007474129896a37b072afb40275464f89e420394b927849ad108875ec"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v9.10.0+0/CUDNN.v9.10.0.aarch64-linux-gnu-cuda_platform+sbsa-cuda+12.0.tar.gz"
[[CUDNN]]
arch = "x86_64"
cuda = "12.0"
git-tree-sha1 = "d715a41d4245970607d56bdb26ada0c1a4b5a0e6"
lazy = true
os = "windows"

    [[CUDNN.download]]
    sha256 = "61cbad8a1136940a0cd5512c820e7e34ea88cb2f1aff2dbad5746edd85eba061"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v9.10.0+0/CUDNN.v9.10.0.x86_64-w64-mingw32-cuda+12.0.tar.gz"
