[[CUDNN]]
arch = "x86_64"
cuda = "10.2"
git-tree-sha1 = "a8af00e0b42406af2d5cbbe9e331000eea73fa4a"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN.download]]
    sha256 = "4949bd467ec7b346533e84d4cb91301ce957e4fdb7db91855ae9236491e06de1"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v8.2.0+1/CUDNN.v8.2.0.x86_64-linux-gnu-cuda+10.2.tar.gz"
[[CUDNN]]
arch = "x86_64"
cuda = "10.2"
git-tree-sha1 = "c7caf7706d760d5dbee8979fee2012c07b465d6a"
lazy = true
os = "windows"

    [[CUDNN.download]]
    sha256 = "fdb60a4d891fc75dd83eddce1a6af8d6eda790e7ae4a9b2a7cf35077076d2dcc"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v8.2.0+1/CUDNN.v8.2.0.x86_64-w64-mingw32-cuda+10.2.tar.gz"
[[CUDNN]]
arch = "x86_64"
cuda = "11.0"
git-tree-sha1 = "bb1eaf334fd2b325446947da715172e0496df66e"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN.download]]
    sha256 = "b00c476862e041f1bf6514bcc6b9a5d25dd7d7599f476a1e584746373dad9a22"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v8.2.0+1/CUDNN.v8.2.0.x86_64-linux-gnu-cuda+11.0.tar.gz"
[[CUDNN]]
arch = "powerpc64le"
cuda = "11.0"
git-tree-sha1 = "d16188b3a8ac6a2a2ecfd9b1de54bccfa558690f"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN.download]]
    sha256 = "c6850d4588080287dde50923aa09e10939058fedb7abb9d14cec756fc08bfade"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v8.2.0+1/CUDNN.v8.2.0.powerpc64le-linux-gnu-cuda+11.0.tar.gz"
[[CUDNN]]
arch = "x86_64"
cuda = "11.0"
git-tree-sha1 = "14e8be90fead9a1ccd1ddd4302228f7458bc03dd"
lazy = true
os = "windows"

    [[CUDNN.download]]
    sha256 = "e613a9e2a76126b0e8741218a006180c1e20560e32cd45e3da48b4f279e15f51"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v8.2.0+1/CUDNN.v8.2.0.x86_64-w64-mingw32-cuda+11.0.tar.gz"
[[CUDNN]]
arch = "x86_64"
cuda = "11.1"
git-tree-sha1 = "634a3eb220b733147e8dd5b0035c271701fff2b9"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN.download]]
    sha256 = "df6e5e1bd8039eaaeccdd22c5e2881de60c6ddc228f4a1d96e4708378d3d89d4"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v8.2.0+1/CUDNN.v8.2.0.x86_64-linux-gnu-cuda+11.1.tar.gz"
[[CUDNN]]
arch = "powerpc64le"
cuda = "11.1"
git-tree-sha1 = "f3426364c03846ab2d361ca71ced0be7d2af3706"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN.download]]
    sha256 = "71404d5f0c58c7a0d68d2ff15701e3444a643c1f368dc8c2104fb1cb52272221"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v8.2.0+1/CUDNN.v8.2.0.powerpc64le-linux-gnu-cuda+11.1.tar.gz"
[[CUDNN]]
arch = "x86_64"
cuda = "11.1"
git-tree-sha1 = "98a6a6a78a73d2ee6564bc131fee506675ada7d2"
lazy = true
os = "windows"

    [[CUDNN.download]]
    sha256 = "60eb726420b8da7c9a445049e926999aa9a724dc870df12a2a9983bc52ca7a70"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v8.2.0+1/CUDNN.v8.2.0.x86_64-w64-mingw32-cuda+11.1.tar.gz"
[[CUDNN]]
arch = "x86_64"
cuda = "11.2"
git-tree-sha1 = "6f58874f8eb803d0865ae4e8edf8b0401a20b12c"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN.download]]
    sha256 = "10cfeeaf7830a94b6aab0b6487a1cb718c6e8fbb0096ad896ebf1462b50f94dd"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v8.2.0+1/CUDNN.v8.2.0.x86_64-linux-gnu-cuda+11.2.tar.gz"
[[CUDNN]]
arch = "powerpc64le"
cuda = "11.2"
git-tree-sha1 = "2fe2a3edfcaf37171afe21775d4ec7deaf88286d"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN.download]]
    sha256 = "cd812b7c2c9fa7814e13908524bdc3bbedbe5cdea50bf91e6187e7d10508caae"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v8.2.0+1/CUDNN.v8.2.0.powerpc64le-linux-gnu-cuda+11.2.tar.gz"
[[CUDNN]]
arch = "x86_64"
cuda = "11.2"
git-tree-sha1 = "90c3657b152d8b88a3f46621babf4ad422dd63a2"
lazy = true
os = "windows"

    [[CUDNN.download]]
    sha256 = "2d4bdbae0de3f5254a32732d0973f151c5f059075cc07ee68ae32d616bc8e87e"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v8.2.0+1/CUDNN.v8.2.0.x86_64-w64-mingw32-cuda+11.2.tar.gz"
[[CUDNN]]
arch = "x86_64"
cuda = "11.3"
git-tree-sha1 = "86ec3c6e93c0c9dbd5dc842f65c30e4a96ceda3b"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN.download]]
    sha256 = "b0e14d1c8b1879637d6deb2725bddefa5200cb0f12437e33eafb4471995b860b"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v8.2.0+1/CUDNN.v8.2.0.x86_64-linux-gnu-cuda+11.3.tar.gz"
[[CUDNN]]
arch = "powerpc64le"
cuda = "11.3"
git-tree-sha1 = "f3d9a5c9d948144eb1ed1f01721f2e557f449b1f"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN.download]]
    sha256 = "66b100226b0283005457a2d917104c8e4b937f8f8553ec15b5f1b9b38f83b0d3"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v8.2.0+1/CUDNN.v8.2.0.powerpc64le-linux-gnu-cuda+11.3.tar.gz"
[[CUDNN]]
arch = "x86_64"
cuda = "11.3"
git-tree-sha1 = "b735e4ed23432df5a4f9f051df799e786c0b7ac1"
lazy = true
os = "windows"

    [[CUDNN.download]]
    sha256 = "0b72ac1360e0981c790a53d94a36fc4987c4dea29bf90355e9fbc5bc03c0b5b7"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v8.2.0+1/CUDNN.v8.2.0.x86_64-w64-mingw32-cuda+11.3.tar.gz"
