[[CUDNN]]
arch = "x86_64"
cuda = "10.2"
git-tree-sha1 = "492b9b82838ad8001f681afa23a408c999f00935"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN.download]]
    sha256 = "edc0db6d82320f4288db765e8f50c18e5952fd2321a8f3099669f192da32f44f"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v8.2.2+0/CUDNN.v8.2.2.x86_64-linux-gnu-cuda+10.2.tar.gz"
[[CUDNN]]
arch = "x86_64"
cuda = "10.2"
git-tree-sha1 = "31308a7ed424357ae42181b362eba2904cc1e6a1"
lazy = true
os = "windows"

    [[CUDNN.download]]
    sha256 = "dfb57aab22768e1d3cf0c15bf5c90bfdc13e057a11cd52d54668ebfeba52441c"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v8.2.2+0/CUDNN.v8.2.2.x86_64-w64-mingw32-cuda+10.2.tar.gz"
[[CUDNN]]
arch = "x86_64"
cuda = "11.0"
git-tree-sha1 = "a24a0ad892cd6eb9bd4189504dfc274450ad0312"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN.download]]
    sha256 = "d65f9769df1887f0315947776b290c933d0c0408513214a9a7a3a2677620f5e9"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v8.2.2+0/CUDNN.v8.2.2.x86_64-linux-gnu-cuda+11.0.tar.gz"
[[CUDNN]]
arch = "powerpc64le"
cuda = "11.0"
git-tree-sha1 = "2f84673862c1be36e154e2009d62d86689948a15"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN.download]]
    sha256 = "b7a38e34b14a7e2434360741782b16761f95975126223505f5de81adfe7b7b0a"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v8.2.2+0/CUDNN.v8.2.2.powerpc64le-linux-gnu-cuda+11.0.tar.gz"
[[CUDNN]]
arch = "x86_64"
cuda = "11.0"
git-tree-sha1 = "4a5344dfa57183a7bef5b1f1fe8223b2bafcc159"
lazy = true
os = "windows"

    [[CUDNN.download]]
    sha256 = "e9cf339d0da1512a0a2c57b28687bb7fd42662ad461b8563ff43c0217f386583"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v8.2.2+0/CUDNN.v8.2.2.x86_64-w64-mingw32-cuda+11.0.tar.gz"
[[CUDNN]]
arch = "aarch64"
cuda = "11.0"
git-tree-sha1 = "793be2ffce912c444fdf0870ef49c5561efda86c"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN.download]]
    sha256 = "2fe5c69654d3bc03a877a6e9ad98177caeb3316907b52ceb2ca8421e809bd718"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v8.2.2+0/CUDNN.v8.2.2.aarch64-linux-gnu-cuda+11.0.tar.gz"
[[CUDNN]]
arch = "x86_64"
cuda = "11.1"
git-tree-sha1 = "1cf0854709c7c6babeeb59908796209499f31db7"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN.download]]
    sha256 = "d93e95f605a3b06c6e1565e89a7bb65b08cc7aa976f405c70d1bfa75d284e3f2"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v8.2.2+0/CUDNN.v8.2.2.x86_64-linux-gnu-cuda+11.1.tar.gz"
[[CUDNN]]
arch = "powerpc64le"
cuda = "11.1"
git-tree-sha1 = "85164b3cffd6540821b3d19a4a88a876cbfd7617"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN.download]]
    sha256 = "8627fc278d3882c1235547a5b930fe2dc9daf248ecc5775ab8423d4e5e1061a4"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v8.2.2+0/CUDNN.v8.2.2.powerpc64le-linux-gnu-cuda+11.1.tar.gz"
[[CUDNN]]
arch = "x86_64"
cuda = "11.1"
git-tree-sha1 = "d3d3808188bbd1ab2d2336ba5fec1412d1d191fc"
lazy = true
os = "windows"

    [[CUDNN.download]]
    sha256 = "034d1475e3e64b7d65ca51c11960e3fc0371ad54ca4cf37af37b92abb69082fa"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v8.2.2+0/CUDNN.v8.2.2.x86_64-w64-mingw32-cuda+11.1.tar.gz"
[[CUDNN]]
arch = "aarch64"
cuda = "11.1"
git-tree-sha1 = "bcab144f640316779fa4f19d8b2946c52e2bf3bc"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN.download]]
    sha256 = "a20e7e85a5f9d7cac06878e74668c0217e831cc3764b3ae0e64d06409b10adec"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v8.2.2+0/CUDNN.v8.2.2.aarch64-linux-gnu-cuda+11.1.tar.gz"
[[CUDNN]]
arch = "x86_64"
cuda = "11.2"
git-tree-sha1 = "cb1b6470eab9ff4acbe788932ff62bc45bff4d8e"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN.download]]
    sha256 = "c06e802b798f77a5e7efeed165b5cea1b74b7d75ed5bbd779c49bc642ca7dfd2"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v8.2.2+0/CUDNN.v8.2.2.x86_64-linux-gnu-cuda+11.2.tar.gz"
[[CUDNN]]
arch = "powerpc64le"
cuda = "11.2"
git-tree-sha1 = "1a18103dd84fa51b22d828eefea8785770cdd32d"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN.download]]
    sha256 = "48a542aca0bae8f37e32fe938351379158f92434fb3ebf8fea1b011c967b4a69"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v8.2.2+0/CUDNN.v8.2.2.powerpc64le-linux-gnu-cuda+11.2.tar.gz"
[[CUDNN]]
arch = "x86_64"
cuda = "11.2"
git-tree-sha1 = "15d5cfa36890308c026d281917e6203ff1857019"
lazy = true
os = "windows"

    [[CUDNN.download]]
    sha256 = "0f38fd201220bc80687bd283657580ba4845da59fddd7fce8700e0822aa37d2c"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v8.2.2+0/CUDNN.v8.2.2.x86_64-w64-mingw32-cuda+11.2.tar.gz"
[[CUDNN]]
arch = "aarch64"
cuda = "11.2"
git-tree-sha1 = "8db3c946a23a40becb29e19ead4a99a9ba696dc1"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN.download]]
    sha256 = "298f2274b7f7b95dc0f7b699c45d7dad4c4fc586ae43b6c7be69cd5389c30d52"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v8.2.2+0/CUDNN.v8.2.2.aarch64-linux-gnu-cuda+11.2.tar.gz"
[[CUDNN]]
arch = "x86_64"
cuda = "11.3"
git-tree-sha1 = "ac6c131ab02095d523f905d0501faf0966d13f5d"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN.download]]
    sha256 = "3809f70fefe57a7f6e74439a0f693b08ce7c8fef039ef8b5de5d4b711293089a"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v8.2.2+0/CUDNN.v8.2.2.x86_64-linux-gnu-cuda+11.3.tar.gz"
[[CUDNN]]
arch = "powerpc64le"
cuda = "11.3"
git-tree-sha1 = "0c8d85a489fb6ed7328ee170632b6f13d697bce4"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN.download]]
    sha256 = "72ee0d78d11cfbf7e73a87d2ff7d7aab40296ad64436baa73bc9c44f3514a4b8"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v8.2.2+0/CUDNN.v8.2.2.powerpc64le-linux-gnu-cuda+11.3.tar.gz"
[[CUDNN]]
arch = "x86_64"
cuda = "11.3"
git-tree-sha1 = "b98c227c218e6b2ac4393bff8c1969dfe6856246"
lazy = true
os = "windows"

    [[CUDNN.download]]
    sha256 = "53fe010de0b9e952bc23e85279fa7129910a3cd8f8c48fcbfa7a7e2cba35300d"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v8.2.2+0/CUDNN.v8.2.2.x86_64-w64-mingw32-cuda+11.3.tar.gz"
[[CUDNN]]
arch = "aarch64"
cuda = "11.3"
git-tree-sha1 = "d38b9534a8aa56abfb94dca54ee8b55f6c6f4ceb"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN.download]]
    sha256 = "ddbeb20ad906ffe911befd6dc5678095cfbeb0ae7aa118fdfcbdfd753c6be611"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v8.2.2+0/CUDNN.v8.2.2.aarch64-linux-gnu-cuda+11.3.tar.gz"
[[CUDNN]]
arch = "x86_64"
cuda = "11.4"
git-tree-sha1 = "793934d761bbcf52eb6fa268b61281fa8480d78f"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN.download]]
    sha256 = "9e84b1d8447b26a3a0763b8176f95a8f8372185b6c1404511721b8ebdb315372"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v8.2.2+0/CUDNN.v8.2.2.x86_64-linux-gnu-cuda+11.4.tar.gz"
[[CUDNN]]
arch = "powerpc64le"
cuda = "11.4"
git-tree-sha1 = "be37ccb4328e35cb87d57b4f334a77f127576115"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN.download]]
    sha256 = "06095dfec7dc7098ad87119f9aaf33a5f73ebfdb7a7011d8e8896522ab21b7f2"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v8.2.2+0/CUDNN.v8.2.2.powerpc64le-linux-gnu-cuda+11.4.tar.gz"
[[CUDNN]]
arch = "x86_64"
cuda = "11.4"
git-tree-sha1 = "58bd87695e9ccdb508cb38be1ab717315ecc9152"
lazy = true
os = "windows"

    [[CUDNN.download]]
    sha256 = "e2d8bb9f193ba39662f97e65db2b6899791c3db669f249c37bef9cf8eae85c4b"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v8.2.2+0/CUDNN.v8.2.2.x86_64-w64-mingw32-cuda+11.4.tar.gz"
[[CUDNN]]
arch = "aarch64"
cuda = "11.4"
git-tree-sha1 = "fbfab979179c92523e99a3791f3e7905a6bedc36"
lazy = true
libc = "glibc"
os = "linux"

    [[CUDNN.download]]
    sha256 = "de4d349311a25e9229f40fa11313072a9003d1ca09e682d5c0913cc9a9df0ad0"
    url = "https://github.com/JuliaBinaryWrappers/CUDNN_jll.jl/releases/download/CUDNN-v8.2.2+0/CUDNN.v8.2.2.aarch64-linux-gnu-cuda+11.4.tar.gz"
