# Autogenerated wrapper script for CUDNN_jll for x86_64-w64-mingw32-cuda+11.6
export libcudnn

using CUDA_loader_jll
JLLWrappers.@generate_wrapper_header("CUDNN")
JLLWrappers.@declare_library_product(libcudnn, "cudnn64_8.dll")
function __init__()
    JLLWrappers.@generate_init_header(CUDA_loader_jll)
    JLLWrappers.@init_library_product(
        libcudnn,
        "bin\\cudnn64_8.dll",
        nothing,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
